/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.itis.model.jooq.schema.Keys;
import ru.itis.model.jooq.schema.Public;
import ru.itis.model.jooq.schema.tables.records.AddressEntityRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressEntity extends TableImpl<AddressEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.address_entity</code>
     */
    public static final AddressEntity ADDRESS_ENTITY = new AddressEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressEntityRecord> getRecordType() {
        return AddressEntityRecord.class;
    }

    /**
     * The column <code>public.address_entity.address_id</code>.
     */
    public final TableField<AddressEntityRecord, UUID> ADDRESS_ID = createField(DSL.name("address_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.address_entity.user_id</code>.
     */
    public final TableField<AddressEntityRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.address_entity.street</code>.
     */
    public final TableField<AddressEntityRecord, String> STREET = createField(DSL.name("street"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.address_entity.city</code>.
     */
    public final TableField<AddressEntityRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.address_entity.zip_code</code>.
     */
    public final TableField<AddressEntityRecord, String> ZIP_CODE = createField(DSL.name("zip_code"), SQLDataType.VARCHAR(10), this, "");

    private AddressEntity(Name alias, Table<AddressEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private AddressEntity(Name alias, Table<AddressEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.address_entity</code> table reference
     */
    public AddressEntity(String alias) {
        this(DSL.name(alias), ADDRESS_ENTITY);
    }

    /**
     * Create an aliased <code>public.address_entity</code> table reference
     */
    public AddressEntity(Name alias) {
        this(alias, ADDRESS_ENTITY);
    }

    /**
     * Create a <code>public.address_entity</code> table reference
     */
    public AddressEntity() {
        this(DSL.name("address_entity"), null);
    }

    public <O extends Record> AddressEntity(Table<O> child, ForeignKey<O, AddressEntityRecord> key) {
        super(child, key, ADDRESS_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AddressEntityRecord> getPrimaryKey() {
        return Keys.ADDRESS_ENTITY_PKEY;
    }

    @Override
    public List<UniqueKey<AddressEntityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ADDRESS_ENTITY_USER_ID_KEY);
    }

    @Override
    public List<ForeignKey<AddressEntityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ADDRESS_ENTITY__ADDRESS_ENTITY_USER_ENTITY_USER_ID_FK);
    }

    private transient UserEntity _userEntity;

    /**
     * Get the implicit join path to the <code>public.user_entity</code> table.
     */
    public UserEntity userEntity() {
        if (_userEntity == null)
            _userEntity = new UserEntity(this, Keys.ADDRESS_ENTITY__ADDRESS_ENTITY_USER_ENTITY_USER_ID_FK);

        return _userEntity;
    }

    @Override
    public AddressEntity as(String alias) {
        return new AddressEntity(DSL.name(alias), this);
    }

    @Override
    public AddressEntity as(Name alias) {
        return new AddressEntity(alias, this);
    }

    @Override
    public AddressEntity as(Table<?> alias) {
        return new AddressEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressEntity rename(String name) {
        return new AddressEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressEntity rename(Name name) {
        return new AddressEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressEntity rename(Table<?> name) {
        return new AddressEntity(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
