/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.itis.model.jooq.schema.Keys;
import ru.itis.model.jooq.schema.Public;
import ru.itis.model.jooq.schema.tables.records.OrderEntityRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderEntity extends TableImpl<OrderEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.order_entity</code>
     */
    public static final OrderEntity ORDER_ENTITY = new OrderEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderEntityRecord> getRecordType() {
        return OrderEntityRecord.class;
    }

    /**
     * The column <code>public.order_entity.order_id</code>.
     */
    public final TableField<OrderEntityRecord, UUID> ORDER_ID = createField(DSL.name("order_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.order_entity.user_id</code>.
     */
    public final TableField<OrderEntityRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.order_entity.order_date</code>.
     */
    public final TableField<OrderEntityRecord, LocalDateTime> ORDER_DATE = createField(DSL.name("order_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.order_entity.total_price</code>.
     */
    public final TableField<OrderEntityRecord, BigDecimal> TOTAL_PRICE = createField(DSL.name("total_price"), SQLDataType.NUMERIC, this, "");

    private OrderEntity(Name alias, Table<OrderEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrderEntity(Name alias, Table<OrderEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.order_entity</code> table reference
     */
    public OrderEntity(String alias) {
        this(DSL.name(alias), ORDER_ENTITY);
    }

    /**
     * Create an aliased <code>public.order_entity</code> table reference
     */
    public OrderEntity(Name alias) {
        this(alias, ORDER_ENTITY);
    }

    /**
     * Create a <code>public.order_entity</code> table reference
     */
    public OrderEntity() {
        this(DSL.name("order_entity"), null);
    }

    public <O extends Record> OrderEntity(Table<O> child, ForeignKey<O, OrderEntityRecord> key) {
        super(child, key, ORDER_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrderEntityRecord> getPrimaryKey() {
        return Keys.ORDER_ENTITY_PKEY;
    }

    @Override
    public List<ForeignKey<OrderEntityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORDER_ENTITY__ORDER_ENTITY_USER_ENTITY_USER_ID_FK);
    }

    private transient UserEntity _userEntity;

    /**
     * Get the implicit join path to the <code>public.user_entity</code> table.
     */
    public UserEntity userEntity() {
        if (_userEntity == null)
            _userEntity = new UserEntity(this, Keys.ORDER_ENTITY__ORDER_ENTITY_USER_ENTITY_USER_ID_FK);

        return _userEntity;
    }

    @Override
    public OrderEntity as(String alias) {
        return new OrderEntity(DSL.name(alias), this);
    }

    @Override
    public OrderEntity as(Name alias) {
        return new OrderEntity(alias, this);
    }

    @Override
    public OrderEntity as(Table<?> alias) {
        return new OrderEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderEntity rename(String name) {
        return new OrderEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderEntity rename(Name name) {
        return new OrderEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderEntity rename(Table<?> name) {
        return new OrderEntity(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, LocalDateTime, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super UUID, ? super UUID, ? super LocalDateTime, ? super BigDecimal, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super UUID, ? super UUID, ? super LocalDateTime, ? super BigDecimal, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
