/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import ru.itis.model.entity.Entity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderProductPojo extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID orderProductId;
    private UUID orderId;
    private UUID productId;

    public OrderProductPojo() {}

    public OrderProductPojo(OrderProductPojo value) {
        this.orderProductId = value.orderProductId;
        this.orderId = value.orderId;
        this.productId = value.productId;
    }

    public OrderProductPojo(
        UUID orderProductId,
        UUID orderId,
        UUID productId
    ) {
        this.orderProductId = orderProductId;
        this.orderId = orderId;
        this.productId = productId;
    }

    /**
     * Getter for <code>public.order_product.order_product_id</code>.
     */
    public UUID getOrderProductId() {
        return this.orderProductId;
    }

    /**
     * Setter for <code>public.order_product.order_product_id</code>.
     */
    public void setOrderProductId(UUID orderProductId) {
        this.orderProductId = orderProductId;
    }

    /**
     * Getter for <code>public.order_product.order_id</code>.
     */
    public UUID getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.order_product.order_id</code>.
     */
    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    /**
     * Getter for <code>public.order_product.product_id</code>.
     */
    public UUID getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>public.order_product.product_id</code>.
     */
    public void setProductId(UUID productId) {
        this.productId = productId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrderProductPojo other = (OrderProductPojo) obj;
        if (this.orderProductId == null) {
            if (other.orderProductId != null)
                return false;
        }
        else if (!this.orderProductId.equals(other.orderProductId))
            return false;
        if (this.orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!this.orderId.equals(other.orderId))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.orderProductId == null) ? 0 : this.orderProductId.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderProductPojo (");

        sb.append(orderProductId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(productId);

        sb.append(")");
        return sb.toString();
    }
}
