/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.UUID;

import ru.itis.model.entity.Entity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductEntityPojo extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID productId;
    private String name;
    private BigDecimal price;

    public ProductEntityPojo() {}

    public ProductEntityPojo(ProductEntityPojo value) {
        this.productId = value.productId;
        this.name = value.name;
        this.price = value.price;
    }

    public ProductEntityPojo(
        UUID productId,
        String name,
        BigDecimal price
    ) {
        this.productId = productId;
        this.name = name;
        this.price = price;
    }

    /**
     * Getter for <code>public.product_entity.product_id</code>.
     */
    public UUID getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>public.product_entity.product_id</code>.
     */
    public void setProductId(UUID productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>public.product_entity.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.product_entity.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.product_entity.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.product_entity.price</code>.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProductEntityPojo other = (ProductEntityPojo) obj;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductEntityPojo (");

        sb.append(productId);
        sb.append(", ").append(name);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
