/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;

import ru.itis.model.entity.Entity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntityPojo extends Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID userId;
    private String name;
    private String phone;

    public UserEntityPojo() {}

    public UserEntityPojo(UserEntityPojo value) {
        this.userId = value.userId;
        this.name = value.name;
        this.phone = value.phone;
    }

    public UserEntityPojo(
        UUID userId,
        String name,
        String phone
    ) {
        this.userId = userId;
        this.name = name;
        this.phone = phone;
    }

    /**
     * Getter for <code>public.user_entity.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.user_entity.user_id</code>.
     */
    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.user_entity.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.user_entity.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.user_entity.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public.user_entity.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserEntityPojo other = (UserEntityPojo) obj;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserEntityPojo (");

        sb.append(userId);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
