/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.itis.model.jooq.schema.tables.AddressEntity;
import ru.itis.model.jooq.schema.tables.OrderEntity;
import ru.itis.model.jooq.schema.tables.OrderProduct;
import ru.itis.model.jooq.schema.tables.ProductEntity;
import ru.itis.model.jooq.schema.tables.UserEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address_entity</code>.
     */
    public final AddressEntity ADDRESS_ENTITY = AddressEntity.ADDRESS_ENTITY;

    /**
     * The table <code>public.order_entity</code>.
     */
    public final OrderEntity ORDER_ENTITY = OrderEntity.ORDER_ENTITY;

    /**
     * The table <code>public.order_product</code>.
     */
    public final OrderProduct ORDER_PRODUCT = OrderProduct.ORDER_PRODUCT;

    /**
     * The table <code>public.product_entity</code>.
     */
    public final ProductEntity PRODUCT_ENTITY = ProductEntity.PRODUCT_ENTITY;

    /**
     * The table <code>public.user_entity</code>.
     */
    public final UserEntity USER_ENTITY = UserEntity.USER_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AddressEntity.ADDRESS_ENTITY,
            OrderEntity.ORDER_ENTITY,
            OrderProduct.ORDER_PRODUCT,
            ProductEntity.PRODUCT_ENTITY,
            UserEntity.USER_ENTITY
        );
    }
}
