/*
 * This file is generated by jOOQ.
 */
package ru.itis.model.jooq.schema;


import ru.itis.model.jooq.schema.tables.AddressEntity;
import ru.itis.model.jooq.schema.tables.OrderEntity;
import ru.itis.model.jooq.schema.tables.OrderProduct;
import ru.itis.model.jooq.schema.tables.ProductEntity;
import ru.itis.model.jooq.schema.tables.UserEntity;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address_entity</code>.
     */
    public static final AddressEntity ADDRESS_ENTITY = AddressEntity.ADDRESS_ENTITY;

    /**
     * The table <code>public.order_entity</code>.
     */
    public static final OrderEntity ORDER_ENTITY = OrderEntity.ORDER_ENTITY;

    /**
     * The table <code>public.order_product</code>.
     */
    public static final OrderProduct ORDER_PRODUCT = OrderProduct.ORDER_PRODUCT;

    /**
     * The table <code>public.product_entity</code>.
     */
    public static final ProductEntity PRODUCT_ENTITY = ProductEntity.PRODUCT_ENTITY;

    /**
     * The table <code>public.user_entity</code>.
     */
    public static final UserEntity USER_ENTITY = UserEntity.USER_ENTITY;
}
